/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as MedicalFileRouteImport } from './routes/medical-file'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorReportsRouteImport } from './routes/doctor.reports'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorVisitRouteImport } from './routes/doctor.visit'
import { Route as DoctorPatientIdRouteImport } from './routes/doctor.patient.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalFileRoute = MedicalFileRouteImport.update({
  id: '/medical-file',
  path: '/medical-file',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorVisitRoute = DoctorVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientIdRoute = DoctorPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/booking': typeof BookingRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/front-desk': typeof FrontDeskRoute
  '/medical-file': typeof MedicalFileRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor/visit': typeof DoctorVisitRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/booking': typeof BookingRoute
  '/front-desk': typeof FrontDeskRoute
  '/medical-file': typeof MedicalFileRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor/visit': typeof DoctorVisitRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/booking': typeof BookingRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/front-desk': typeof FrontDeskRoute
  '/medical-file': typeof MedicalFileRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor/visit': typeof DoctorVisitRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/booking'
    | '/doctor'
    | '/front-desk'
    | '/medical-file'
    | '/prescriptions'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctor/visit'
    | '/doctor/'
    | '/doctor/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/booking'
    | '/front-desk'
    | '/medical-file'
    | '/prescriptions'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctor/visit'
    | '/doctor'
    | '/doctor/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/booking'
    | '/doctor'
    | '/front-desk'
    | '/medical-file'
    | '/prescriptions'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctor/visit'
    | '/doctor/'
    | '/doctor/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BookingRoute: typeof BookingRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  FrontDeskRoute: typeof FrontDeskRoute
  MedicalFileRoute: typeof MedicalFileRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-file': {
      id: '/medical-file'
      path: '/medical-file'
      fullPath: '/medical-file'
      preLoaderRoute: typeof MedicalFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/visit': {
      id: '/doctor/visit'
      path: '/visit'
      fullPath: '/doctor/visit'
      preLoaderRoute: typeof DoctorVisitRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patient/$id': {
      id: '/doctor/patient/$id'
      path: '/patient/$id'
      fullPath: '/doctor/patient/$id'
      preLoaderRoute: typeof DoctorPatientIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorVisitRoute: typeof DoctorVisitRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientIdRoute: typeof DoctorPatientIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorVisitRoute: DoctorVisitRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientIdRoute: DoctorPatientIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BookingRoute: BookingRoute,
  DoctorRoute: DoctorRouteWithChildren,
  FrontDeskRoute: FrontDeskRoute,
  MedicalFileRoute: MedicalFileRoute,
  PrescriptionsRoute: PrescriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
